// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayBill.Data;

#nullable disable

namespace PayBill.Migrations
{
    [DbContext(typeof(PayBillDbContext))]
    [Migration("20240613041105_AddReceiptEmployee")]
    partial class AddReceiptEmployee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PayBill.Models.Dish", b =>
                {
                    b.Property<int>("ID_Dish")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Dish_Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Dish_Price")
                        .HasColumnType("longtext");

                    b.Property<int>("Is_For_Employee")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ID_Dish");

                    b.ToTable("T_Dish", (string)null);
                });

            modelBuilder.Entity("PayBill.Models.Employee", b =>
                {
                    b.Property<string>("ID_Employee")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Employee_Name")
                        .HasColumnType("longtext");

                    b.HasKey("ID_Employee");

                    b.ToTable("T_Employee", (string)null);
                });

            modelBuilder.Entity("PayBill.Models.Receipt", b =>
                {
                    b.Property<string>("ID_Receipt")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Create_Date")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Total_Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ID_Receipt");

                    b.ToTable("T_Receipt", (string)null);
                });

            modelBuilder.Entity("PayBill.Models.Receipt_Details", b =>
                {
                    b.Property<string>("ID_Receipt_Details")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Create_Date")
                        .HasColumnType("longtext");

                    b.Property<int>("ID_Dish")
                        .HasColumnType("int");

                    b.Property<string>("ID_Receipt")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID_Receipt_Details");

                    b.ToTable("T_Receipt_Detail", (string)null);
                });

            modelBuilder.Entity("PayBill.Models.Receipt_Employee", b =>
                {
                    b.Property<string>("ID_Receipt_Details")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Create_Date")
                        .HasColumnType("longtext");

                    b.Property<int>("ID_Dish")
                        .HasColumnType("int");

                    b.Property<string>("ID_Employee")
                        .HasColumnType("longtext");

                    b.Property<string>("ID_Receipt")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID_Receipt_Details");

                    b.ToTable("T_Receipt_Employee", (string)null);
                });

            modelBuilder.Entity("PayBill.Models.Tables", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NameTable")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("T_Tables", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
